---
# tasks file for install-backend-db

## Debconf-utils needed to get the database password without interacting
## with the mysql install
- name: Install debconf-utils
  apt:
    pkg: debconf-utils
    state: present
  become: yes
  become_method: sudo

- name: Add mysql root password to debconf
  debconf:
    name: mysql-server
    question: mysql-server/root_password
    vtype: password
    value: "{{ DB_PASSWORD }}"
  become: yes
  become_method: sudo

- name: Add mysql root password again to debconf
  debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    vtype: password
    value: "{{ DB_PASSWORD }}"
  become: yes
  become_method: sudo

- name: Install python-mysqldb package
  apt:
    pkg: python-mysqldb
    state: present
  become: yes
  become_method: sudo
  
- name: Install mySQL package
  apt:
    pkg: mysql-server
    state: present
  become: yes
  become_method: sudo

- name: Update bind-address of mysql
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=bind-address
            value='0.0.0.0'
  become: yes
  become_method: sudo

- name: Restart mysql service
  service:
    name: mysql
    state: restarted
  become: yes
  become_method: sudo
  
- name: Create Openstack Databases
  mysql_db:
    name: "{{ item }}"
    state: present
    login_user: "{{ DB_ADMIN }}"
    login_password: "{{ DB_PASSWORD }}"
  with_items:
    - keystone
    - glance
    - cinder
    - neutron
    - nova
  become: yes
  become_method: sudo

- name: Create Openstack DB Users
  mysql_user:
    name: "{{ item }}_dbu"
    priv: '{{ item }}.*:ALL,GRANT'
    state: present
    login_user: "{{ DB_ADMIN }}"
    login_password: "{{ DB_PASSWORD }}"
  with_items:
    - keystone
    - glance
    - cinder
    - neutron
    - nova
  become: yes
  become_method: sudo
