---
# tasks file for keystone-install

- name: Install keystone package
  apt:
    name: keystone
    state: present
  become: yes
  become_method: sudo

- name: Install apache2 package
  apt:
    name: apache2
    state: present
  become: yes
  become_method: sudo

- name: Install libapache2-mod-wsgi pacage
  apt:
    name: libapache2-mod-wsgi
    state: present
  become: yes
  become_method: sudo

- name: Install python-openstack client
  apt:
    name: python-openstackclient
    state: present
  become: yes
  become_method: sudo

- name: Install python3-openstack client
  apt:
    name: python3-openstackclient
    state: present
  become: yes
  become_method: sudo

- name: Run keystone db_sync
  shell: /bin/sh -c "keystone-manage db_sync" keystone
  become: yes
  become_method: sudo

